version: '3'
services:
  node:
    build:
      context: .
      dockerfile: ./docker/node.Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - ./src:/src
      - ./public:/public

  web:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    ports:
      - 8443:443
    volumes:
      - ./public:/usr/share/nginx/html:ro
